# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install errorhandler
      - name: Run format checker on pull request
        if: ${{github.event_name == 'pull_request'}}
        env:
          BASE_SHA: ${{github.event.pull_request.base.sha}}
          HEAD_SHA: ${{github.event.pull_request.head.sha}}
        run: |
          commit_list=$(git log --oneline $BASE_SHA..$HEAD_SHA | cut -d " " -f 1)
          python ./format_checker/main.py $commit_list
      - name: Run format checker on push
        if: ${{github.event_name == 'push'}}
        env:
          BASE_SHA: ${{github.event.before}}
          HEAD_SHA: ${{github.event.after}}
        run: |
          commit_list=$(git log --oneline $BASE_SHA..$HEAD_SHA | cut -d " " -f 1)
          python ./format_checker/main.py $commit_list